# Generated by Django 5.1.5 on 2025-03-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_attendance', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_adm', models.IntegerField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attendance.programme')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attendance.teacher')),
            ],
        ),
    ]
