# Generated by Django 5.1.5 on 2025-03-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_attendance', '0004_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
