# Generated by Django 5.1.5 on 2025-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_attendance', '0005_teacher_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
