# Generated by Django 5.1.6 on 2025-02-11 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('hour_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour_no', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('pgm_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgm_name', models.CharField(max_length=255)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('reg_num', models.CharField(max_length=255, unique=True)),
                ('year_adm', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('pgm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=255)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.department')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_adm', models.IntegerField()),
                ('pgm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.programme')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PresentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.hour')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.student')),
            ],
            options={
                'unique_together': {('hour', 'stud')},
            },
        ),
        migrations.CreateModel(
            name='StudentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.item')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_attandance.student')),
            ],
            options={
                'unique_together': {('stud', 'item')},
            },
        ),
    ]
